language: python

python:
    - "2.6"
    - "2.7"

sudo: false

env:
    - DJANGO=1.5.12 TEST_DATABASE_NAME=serrano TEST_DATABASE_USER=postgres
    - DJANGO=1.6.10 TEST_DATABASE_NAME=serrano TEST_DATABASE_USER=postgres

addons:
    postgresql: "9.3"

services:
    - memcached
    - redis-server

before_install:
    - bash bin/check_signoff.sh
    - pip install -q flake8
    - flake8

install:
    - pip install -q coverage Django==$DJANGO
    - pip install -q -r requirements.txt
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors ordereddict importlib; fi"

before_script:
    - psql -U postgres -c 'CREATE DATABASE serrano;'

script:
    - coverage run test_suite.py

after_success:
    - pip install -q coveralls
    - coveralls
